#ifndef SANDY_ESP32CAM_CONFIG_H
#define SANDY_ESP32CAM_CONFIG_H

#ifndef CAMERA_USE_STATIC_IP
  #define CAMERA_USE_STATIC_IP true
#endif

#ifndef CAMERA_LOCAL_IP_1
  #define CAMERA_LOCAL_IP_1 192
  #define CAMERA_LOCAL_IP_2 168
  #define CAMERA_LOCAL_IP_3 1
  #define CAMERA_LOCAL_IP_4 150
#endif

#ifndef CAMERA_GATEWAY_1
  #define CAMERA_GATEWAY_1 192
  #define CAMERA_GATEWAY_2 168
  #define CAMERA_GATEWAY_3 1
  #define CAMERA_GATEWAY_4 1
#endif

#ifndef CAMERA_SUBNET_1
  #define CAMERA_SUBNET_1 255
  #define CAMERA_SUBNET_2 255
  #define CAMERA_SUBNET_3 255
  #define CAMERA_SUBNET_4 0
#endif

#ifndef CAMERA_DEFAULT_ENABLED
  #define CAMERA_DEFAULT_ENABLED false
#endif

#ifndef CAMERA_DEFAULT_FRAME_SIZE
  #define CAMERA_DEFAULT_FRAME_SIZE FRAMESIZE_VGA
#endif

#ifndef CAMERA_DEFAULT_JPEG_QUALITY
  #define CAMERA_DEFAULT_JPEG_QUALITY 12
#endif

#ifndef CAMERA_DEFAULT_FB_COUNT
  #define CAMERA_DEFAULT_FB_COUNT 2
#endif

#ifndef CAMERA_VERTICAL_FLIP
  #define CAMERA_VERTICAL_FLIP 1
#endif

#ifndef CAMERA_STREAM_FRAME_DELAY_MS
  #define CAMERA_STREAM_FRAME_DELAY_MS 80
#endif

#endif
