#ifndef SANDY_ESP32CAM_SECRETS_H
#define SANDY_ESP32CAM_SECRETS_H

#define SECRET_SSID "YOUR_WIFI_SSID"
#define SECRET_OPTIONAL_PASS "YOUR_WIFI_PASSWORD"

#define CAMERA_DEVICE_LOGIN_NAME "YOUR_CAMERA_DEVICE_LOGIN_NAME"
#define CAMERA_DEVICE_KEY "YOUR_CAMERA_DEVICE_KEY"
#define CAMERA_SNAPSHOT_TOKEN "YOUR_CAMERA_SNAPSHOT_TOKEN"
#define CAMERA_CONTROL_TOKEN "YOUR_CAMERA_CONTROL_TOKEN"
#define CAMERA_HTTP_USER "YOUR_CAMERA_HTTP_USER"
#define CAMERA_HTTP_PASS "YOUR_CAMERA_HTTP_PASS"

#endif
