// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = CAMERA_DEVICE_LOGIN_NAME;

const char SSID[]               = SECRET_SSID;
const char PASS[]               = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[]         = CAMERA_DEVICE_KEY;

void onCameraModeChange();
void onCameraPowerChange();
void onCameraSnapshotChange();
void onCameraStreamChange();
void onFullModeEnabledChange();
void onSecretArmedChange();

String cameraMode;
String cameraStatus;
bool cameraPower;
bool cameraSnapshot;
bool cameraStream;
bool fullModeEnabled;
bool secretArmed;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cameraMode, READWRITE, ON_CHANGE, onCameraModeChange);
  ArduinoCloud.addProperty(cameraStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cameraPower, READWRITE, ON_CHANGE, onCameraPowerChange);
  ArduinoCloud.addProperty(cameraSnapshot, READWRITE, ON_CHANGE, onCameraSnapshotChange);
  ArduinoCloud.addProperty(cameraStream, READWRITE, ON_CHANGE, onCameraStreamChange);
  ArduinoCloud.addProperty(fullModeEnabled, READWRITE, ON_CHANGE, onFullModeEnabledChange);
  ArduinoCloud.addProperty(secretArmed, READWRITE, ON_CHANGE, onSecretArmedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
