// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#ifndef ESP32CAM_STREAM_THING_PROPERTIES_H
#define ESP32CAM_STREAM_THING_PROPERTIES_H

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

void initProperties() {
  ArduinoCloud.setBoardId(SECRET_DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(SECRET_DEVICE_KEY);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SECRET_SSID, SECRET_OPTIONAL_PASS);

#endif
