#ifndef SANDY_SECRETS_H
#define SANDY_SECRETS_H

const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

#define SANDY_DEVICE_LOGIN_NAME "YOUR_MAIN_DEVICE_LOGIN_NAME"
#define SANDY_DEVICE_KEY "YOUR_MAIN_DEVICE_KEY"

#endif
