// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9ae4816c-5a9e-43ae-9387-bda18f86dc61";

const char* SSID = WIFI_SSID;
const char* PASS = WIFI_PASSWORD;
const char* DEVICE_KEY = "KfR#67T3vcHJ0NqtiKePT#@6A";

void onBuzzerCommandChange();
void onMoodStateChange();
void onServoAngleChange();
void onAutonomousModeChange();

String buzzerCommand;
String moodState;
String statusText;
float distanceCm;
int servoAngle;
bool autonomousMode;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(buzzerCommand, READWRITE, ON_CHANGE, onBuzzerCommandChange);
  ArduinoCloud.addProperty(moodState, READWRITE, ON_CHANGE, onMoodStateChange);
  ArduinoCloud.addProperty(statusText, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(distanceCm, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(servoAngle, READWRITE, ON_CHANGE, onServoAngleChange);
  ArduinoCloud.addProperty(autonomousMode, READWRITE, ON_CHANGE, onAutonomousModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

